VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
UNICODEMAP_ENABLE = yes

LTO_ENABLE = yes

# todo set to no again
VIAL_INSECURE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no