VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
AUDIO_ENABLE = no
UNICODE_ENABLE = yes
COMMAND_ENABLE = no

LTO_ENABLE = yes

# todo set to no again
VIAL_INSECURE = yes